spring.application.name=management
server.port = 8100
# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:emsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=true

# Hibernate Properties (Auto-Create Tables)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis Configuration
spring.redis.host=localhost
spring.redis.port=6379
spring.cache.type=redis
